import "./general.css";

export const metadata = {
  title: "To Do App",
  description: "Generated by Hamid",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1>To Do App</h1>
        {children}
      </body>
    </html>
  );
}
