import "./general.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });
export const metadata = {
  title: "To Do App",
  description: "Generated by Hamid",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <h1>To Do App</h1>
        {children}
      </body>
    </html>
  );
}
